import React from 'react';

import css from './CSS';
import RestaurantView from './RestaurantView';

import {
  Image,
  View,
  TouchableHighlight,
  ListView,
  Text,
  Component
} from 'react-native';

// this const to be deleted after style has been changed
const LISTING = [ { _id: '574c75705c1baee60d501410',
    restaurantId: '0',
    name: 'Aestus',
    imgPath: 'https://drive.google.com/uc?export=view&id=0B7Q--fIbe5tbVE5Cd0k0M0dzWms',
    location: 'Santa Monica',
    latitude: 34.020399,
    longitude: -118.4973161,
    price: '31-50',
    address: '507 Wilshire Blvd, Santa Monica, CA 90401',
    phone_number: '(424) 268-4433',
    reviews: '4.0/5',
    notes: '',
    website: 'http://www.aestusrestaurant.com/',
    created_at: '2016-05-30T17:16:32.948Z',
    updated_at: '2016-05-30T17:16:32.948Z',
    __v: 0,
    food_types:
     [ { _id: '574c75705c1baee60d501411',
         vegan: false,
         thai: false,
         tapas: false,
         sushi_bar: false,
         sushi: false,
         steakhouse: false,
         south_american: false,
         seasonal_or_local: false,
         seafood: false,
         pizza: false,
         middle_eastern: false,
         mexican: false,
         korean: false,
         japanese: false,
         italian: false,
         indian: false,
         greek: false,
         german: false,
         fusion: false,
         french: false,
         chinese: false,
         british: false,
         bakery: false,
         asian: false,
         all_american: true } ],
    menu:
     [ { meal: 'Lunch',
         _id: '574c75705c1baee60d501434',
         categories:
          [ { category_name: 'Small Plates',
              _id: '574c75705c1baee60d501448',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75705c1baee60d50144e' },
                 { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75705c1baee60d50144d' },
                 { dish_name: 'Smoked Salmon Dip',
                   description: 'celery, scallions, aioli',
                   _id: '574c75705c1baee60d50144c' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, yuzu kosho, celtuse, wood sorrel',
                   _id: '574c75705c1baee60d50144b' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75705c1baee60d50144a' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75705c1baee60d501449' } ] },
            { category_name: 'Sandwiches',
              _id: '574c75705c1baee60d501442',
              dishes:
               [ { dish_name: 'Pulled Chicken Sandwich',
                   description: 'house bbq sauce, slaw, pickle',
                   _id: '574c75705c1baee60d501447' },
                 { dish_name: 'Grilled Cheese',
                   description: 'raclette, gruyere, cheddar, bechamel',
                   _id: '574c75705c1baee60d501446' },
                 { dish_name: 'Steak Sandwich',
                   description: 'shallot marmalade, horseradish, cream, arugula, steak sauce',
                   _id: '574c75705c1baee60d501445' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries ',
                   _id: '574c75705c1baee60d501444' },
                 { dish_name: 'Albacore Burger',
                   description: 'sriracha aoili, scallion, ginger, soy, avocado, furikake, sesame bun, fries',
                   _id: '574c75705c1baee60d501443' } ] },
            { category_name: 'Salads',
              _id: '574c75705c1baee60d50143c',
              dishes:
               [ { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75705c1baee60d501441' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75705c1baee60d501440' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75705c1baee60d50143f' },
                 { dish_name: 'Waldorf Salad',
                   description: 'potatoes, grapes, walnuts, mixed greens, herbed buttlermilk',
                   _id: '574c75705c1baee60d50143e' },
                 { dish_name: 'Nicoise',
                   description: 'albacore, egg, olives, beans, tomatoes',
                   _id: '574c75705c1baee60d50143d' } ] },
            { category_name: 'Mains',
              _id: '574c75705c1baee60d501438',
              dishes:
               [ { dish_name: 'Housemade Tagliatelle',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75705c1baee60d50143b' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75705c1baee60d50143a' },
                 { dish_name: 'Omelette',
                   description: 'cheddar, toast, greens',
                   _id: '574c75705c1baee60d501439' } ] },
            { category_name: 'Sides',
              _id: '574c75705c1baee60d501435',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75705c1baee60d501437' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75705c1baee60d501436' } ] } ] },
       { meal: 'Dinner',
         _id: '574c75705c1baee60d501412',
         categories:
          [ { category_name: 'For the Table',
              _id: '574c75705c1baee60d50142e',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75705c1baee60d501433' },
                 { dish_name: 'Eggplant Caponata',
                   description: 'peppers, onions, olives, capers',
                   _id: '574c75705c1baee60d501432' },
                 { dish_name: 'Chicken Fritters',
                   description: 'adoba, black pepper aoili, serrano, pickled green garlic',
                   _id: '574c75705c1baee60d501431' },
                 { dish_name: 'Smoked Salmon Rillettes',
                   description: 'celery, scallions, aioli',
                   _id: '574c75705c1baee60d501430' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75705c1baee60d50142f' } ] },
            { category_name: 'Small Plates',
              _id: '574c75705c1baee60d501425',
              dishes:
               [ { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75705c1baee60d50142d' },
                 { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75705c1baee60d50142c' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75705c1baee60d50142b' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75705c1baee60d50142a' },
                 { dish_name: 'English Pea Risotto',
                   description: 'carrots, bacon, meyer lemon, pea tendrils',
                   _id: '574c75705c1baee60d501429' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, celtuse, sorrel',
                   _id: '574c75705c1baee60d501428' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75705c1baee60d501427' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75705c1baee60d501426' } ] },
            { category_name: 'Main',
              _id: '574c75705c1baee60d50141d',
              dishes:
               [ { dish_name: 'Housemade Fettuccine',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75705c1baee60d501424' },
                 { dish_name: 'Grilled Branzino',
                   description: 'chermoula, braised escarole, lemon',
                   _id: '574c75705c1baee60d501423' },
                 { dish_name: 'Wood\'s Fishery Shrimp',
                   description: 'romesco, asparagus, aioli, parsley',
                   _id: '574c75705c1baee60d501422' },
                 { dish_name: 'Fire-roasted Chicken',
                   description: 'hummus, cucumber raita, grilled bread',
                   _id: '574c75705c1baee60d501421' },
                 { dish_name: 'Peads & Barnetts Pork Chop',
                   description: 'flageolets ragout, baby carrots, mustardd',
                   _id: '574c75705c1baee60d501420' },
                 { dish_name: 'Steak Frites',
                   description: '8 oz. new york prime, au poivre',
                   _id: '574c75705c1baee60d50141f' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries',
                   _id: '574c75705c1baee60d50141e' } ] },
            { category_name: 'Sides',
              _id: '574c75705c1baee60d501418',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75705c1baee60d50141c' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75705c1baee60d50141b' },
                 { dish_name: 'Grilled Sprouted Broccoli',
                   description: 'meyer lemon, basil',
                   _id: '574c75705c1baee60d50141a' },
                 { dish_name: 'Roasted Fingerling Potatoes',
                   description: '',
                   _id: '574c75705c1baee60d501419' } ] },
            { category_name: 'Desserts',
              _id: '574c75705c1baee60d501413',
              dishes:
               [ { dish_name: 'Chocolate Chip Cookies and Cinnamon Milk',
                   description: '',
                   _id: '574c75705c1baee60d501417' },
                 { dish_name: 'Lemon Posset',
                   description: '',
                   _id: '574c75705c1baee60d501416' },
                 { dish_name: 'Chocolate Cake',
                   description: '',
                   _id: '574c75705c1baee60d501415' },
                 { dish_name: 'Blackberry Cobbler',
                   description: '',
                   _id: '574c75705c1baee60d501414' } ] } ] } ],
    meals:
     [ { _id: '574c75705c1baee60d50144f',
         lunch: true,
         happy_hour: false,
         drinks: false,
         dinner: true,
         coffee: false,
         brunch: false,
         breakfast: false } ],
    tags:
     [ { _id: '574c75705c1baee60d501450',
         worth_the_lines: false,
         wine_bar: false,
         vegetarian_options: false,
         vegan_options: false,
         upscale: false,
         trendy: true,
         tasting_menu: false,
         takes_walk_ins: false,
         takes_dinner_reservations: false,
         take_out_options: false,
         sweet_treat: false,
         swanky: false,
         special_occasion: false,
         snack: false,
         small_plates: false,
         shareable: false,
         share_plates: false,
         secret: false,
         seat_yourself: false,
         scenery: false,
         rotating_menu: false,
         romantic: false,
         quiet: true,
         private_room: false,
         prime_location: false,
         pastries: false,
         outdoor_seating: false,
         outdoor_dining: false,
         organic_beer_and_wine: false,
         organic: false,
         order_at_counter: false,
         open_late: false,
         no_reservations: false,
         new_restaurant: false,
         locals: false,
         lively_bar_area: false,
         lively: false,
         karaoke: false,
         innovative: false,
         hotspot: false,
         hotel_dining: false,
         hidden_gem: false,
         healthy_options: false,
         hard_to_get_a_table: false,
         happy_hour: false,
         great_view: false,
         good_for_parents: false,
         good_for_lunch: false,
         good_for_groups: false,
         good_drinks: true,
         good_ambiance: false,
         gluten_free_options: false,
         gastropub: false,
         fusion: false,
         fun: false,
         foodie_famous: true,
         first_date: false,
         farm_to_table: true,
         fancy: false,
         famous_chef: false,
         family_friendly: false,
         dog_friendly: false,
         dietary_restriction_friendly: false,
         date_spot: false,
         date_night: true,
         communal_tables: false,
         classy: false,
         chef_inventive: false,
         celeb_spotting: false,
         casual: false,
         cafe: false,
         burgers: false,
         beer_selection: false,
         beer_and_wine: false,
         bar_seating: false,
         bar_scene: false,
         bar_area: false,
         bar: false,
         baked_goods: false,
         authentic_takeout: false,
         authentic: false,
         afternoon: false } ] },
  { _id: '574c75715c1baee60d501451',
    restaurantId: '1',
    name: 'Art\'s Table',
    imgPath: 'https://drive.google.com/uc?export=view&id=0B7Q--fIbe5tbTkJzVVBoSGdkazQ',
    location: 'Santa Monica',
    latitude: 34.0290783,
    longitude: -118.498672,
    price: '21-30',
    address: '1002 Montana Ave, Santa Monica, CA 90403',
    phone_number: '(310) 395-2500',
    reviews: '4.0/5',
    notes: '',
    website: 'http://www.artstablesm.com/',
    created_at: '2016-05-30T17:16:33.190Z',
    updated_at: '2016-05-30T17:16:33.190Z',
    __v: 0,
    food_types:
     [ { _id: '574c75715c1baee60d501452',
         vegan: false,
         thai: false,
         tapas: false,
         sushi_bar: false,
         sushi: false,
         steakhouse: false,
         south_american: false,
         seasonal_or_local: false,
         seafood: false,
         pizza: false,
         middle_eastern: false,
         mexican: false,
         korean: false,
         japanese: false,
         italian: false,
         indian: false,
         greek: false,
         german: false,
         fusion: false,
         french: false,
         chinese: false,
         british: false,
         bakery: false,
         asian: false,
         all_american: true } ],
    menu:
     [ { meal: 'Lunch',
         _id: '574c75715c1baee60d501475',
         categories:
          [ { category_name: 'Small Plates',
              _id: '574c75715c1baee60d501489',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d50148f' },
                 { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d50148e' },
                 { dish_name: 'Smoked Salmon Dip',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d50148d' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, yuzu kosho, celtuse, wood sorrel',
                   _id: '574c75715c1baee60d50148c' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d50148b' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d50148a' } ] },
            { category_name: 'Sandwiches',
              _id: '574c75715c1baee60d501483',
              dishes:
               [ { dish_name: 'Pulled Chicken Sandwich',
                   description: 'house bbq sauce, slaw, pickle',
                   _id: '574c75715c1baee60d501488' },
                 { dish_name: 'Grilled Cheese',
                   description: 'raclette, gruyere, cheddar, bechamel',
                   _id: '574c75715c1baee60d501487' },
                 { dish_name: 'Steak Sandwich',
                   description: 'shallot marmalade, horseradish, cream, arugula, steak sauce',
                   _id: '574c75715c1baee60d501486' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries ',
                   _id: '574c75715c1baee60d501485' },
                 { dish_name: 'Albacore Burger',
                   description: 'sriracha aoili, scallion, ginger, soy, avocado, furikake, sesame bun, fries',
                   _id: '574c75715c1baee60d501484' } ] },
            { category_name: 'Salads',
              _id: '574c75715c1baee60d50147d',
              dishes:
               [ { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d501482' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d501481' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d501480' },
                 { dish_name: 'Waldorf Salad',
                   description: 'potatoes, grapes, walnuts, mixed greens, herbed buttlermilk',
                   _id: '574c75715c1baee60d50147f' },
                 { dish_name: 'Nicoise',
                   description: 'albacore, egg, olives, beans, tomatoes',
                   _id: '574c75715c1baee60d50147e' } ] },
            { category_name: 'Mains',
              _id: '574c75715c1baee60d501479',
              dishes:
               [ { dish_name: 'Housemade Tagliatelle',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d50147c' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d50147b' },
                 { dish_name: 'Omelette',
                   description: 'cheddar, toast, greens',
                   _id: '574c75715c1baee60d50147a' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d501476',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d501478' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d501477' } ] } ] },
       { meal: 'Dinner',
         _id: '574c75715c1baee60d501453',
         categories:
          [ { category_name: 'For the Table',
              _id: '574c75715c1baee60d50146f',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d501474' },
                 { dish_name: 'Eggplant Caponata',
                   description: 'peppers, onions, olives, capers',
                   _id: '574c75715c1baee60d501473' },
                 { dish_name: 'Chicken Fritters',
                   description: 'adoba, black pepper aoili, serrano, pickled green garlic',
                   _id: '574c75715c1baee60d501472' },
                 { dish_name: 'Smoked Salmon Rillettes',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d501471' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d501470' } ] },
            { category_name: 'Small Plates',
              _id: '574c75715c1baee60d501466',
              dishes:
               [ { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d50146e' },
                 { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d50146d' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d50146c' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d50146b' },
                 { dish_name: 'English Pea Risotto',
                   description: 'carrots, bacon, meyer lemon, pea tendrils',
                   _id: '574c75715c1baee60d50146a' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, celtuse, sorrel',
                   _id: '574c75715c1baee60d501469' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d501468' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d501467' } ] },
            { category_name: 'Main',
              _id: '574c75715c1baee60d50145e',
              dishes:
               [ { dish_name: 'Housemade Fettuccine',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d501465' },
                 { dish_name: 'Grilled Branzino',
                   description: 'chermoula, braised escarole, lemon',
                   _id: '574c75715c1baee60d501464' },
                 { dish_name: 'Wood\'s Fishery Shrimp',
                   description: 'romesco, asparagus, aioli, parsley',
                   _id: '574c75715c1baee60d501463' },
                 { dish_name: 'Fire-roasted Chicken',
                   description: 'hummus, cucumber raita, grilled bread',
                   _id: '574c75715c1baee60d501462' },
                 { dish_name: 'Peads & Barnetts Pork Chop',
                   description: 'flageolets ragout, baby carrots, mustardd',
                   _id: '574c75715c1baee60d501461' },
                 { dish_name: 'Steak Frites',
                   description: '8 oz. new york prime, au poivre',
                   _id: '574c75715c1baee60d501460' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries',
                   _id: '574c75715c1baee60d50145f' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d501459',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d50145d' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d50145c' },
                 { dish_name: 'Grilled Sprouted Broccoli',
                   description: 'meyer lemon, basil',
                   _id: '574c75715c1baee60d50145b' },
                 { dish_name: 'Roasted Fingerling Potatoes',
                   description: '',
                   _id: '574c75715c1baee60d50145a' } ] },
            { category_name: 'Desserts',
              _id: '574c75715c1baee60d501454',
              dishes:
               [ { dish_name: 'Chocolate Chip Cookies and Cinnamon Milk',
                   description: '',
                   _id: '574c75715c1baee60d501458' },
                 { dish_name: 'Lemon Posset',
                   description: '',
                   _id: '574c75715c1baee60d501457' },
                 { dish_name: 'Chocolate Cake',
                   description: '',
                   _id: '574c75715c1baee60d501456' },
                 { dish_name: 'Blackberry Cobbler',
                   description: '',
                   _id: '574c75715c1baee60d501455' } ] } ] } ],
    meals:
     [ { _id: '574c75715c1baee60d501490',
         lunch: true,
         happy_hour: false,
         drinks: false,
         dinner: true,
         coffee: false,
         brunch: false,
         breakfast: true } ],
    tags:
     [ { _id: '574c75715c1baee60d501491',
         worth_the_lines: false,
         wine_bar: true,
         vegetarian_options: false,
         vegan_options: false,
         upscale: false,
         trendy: false,
         tasting_menu: false,
         takes_walk_ins: false,
         takes_dinner_reservations: false,
         take_out_options: false,
         sweet_treat: false,
         swanky: false,
         special_occasion: false,
         snack: false,
         small_plates: true,
         shareable: false,
         share_plates: false,
         secret: false,
         seat_yourself: false,
         scenery: false,
         rotating_menu: false,
         romantic: false,
         quiet: false,
         private_room: false,
         prime_location: false,
         pastries: false,
         outdoor_seating: false,
         outdoor_dining: false,
         organic_beer_and_wine: false,
         organic: false,
         order_at_counter: false,
         open_late: false,
         no_reservations: false,
         new_restaurant: false,
         locals: false,
         lively_bar_area: false,
         lively: false,
         karaoke: false,
         innovative: false,
         hotspot: false,
         hotel_dining: false,
         hidden_gem: false,
         healthy_options: false,
         hard_to_get_a_table: false,
         happy_hour: false,
         great_view: false,
         good_for_parents: false,
         good_for_lunch: false,
         good_for_groups: false,
         good_drinks: false,
         good_ambiance: false,
         gluten_free_options: false,
         gastropub: false,
         fusion: false,
         fun: false,
         foodie_famous: false,
         first_date: false,
         farm_to_table: false,
         fancy: false,
         famous_chef: false,
         family_friendly: false,
         dog_friendly: false,
         dietary_restriction_friendly: false,
         date_spot: false,
         date_night: false,
         communal_tables: false,
         classy: false,
         chef_inventive: false,
         celeb_spotting: false,
         casual: true,
         cafe: false,
         burgers: false,
         beer_selection: false,
         beer_and_wine: false,
         bar_seating: false,
         bar_scene: false,
         bar_area: false,
         bar: false,
         baked_goods: false,
         authentic_takeout: false,
         authentic: false,
         afternoon: false } ] },
  { _id: '574c75715c1baee60d501492',
    restaurantId: '2',
    name: 'Belcampo',
    imgPath: 'https://drive.google.com/uc?export=view&id=0B7Q--fIbe5tbTVR0blRxTlRxTDA',
    location: 'Santa Monica',
    latitude: 34.02408580000001,
    longitude: -118.4917351,
    price: '31-50',
    address: '1026 Wilshire Blvd, Santa Monica, CA 90401',
    phone_number: '(424) 744-8008',
    reviews: '3.5/5',
    notes: '',
    website: 'http://www.belcampo.com/restaurant/santa-monica/',
    created_at: '2016-05-30T17:16:33.416Z',
    updated_at: '2016-05-30T17:16:33.416Z',
    __v: 0,
    food_types:
     [ { _id: '574c75715c1baee60d501493',
         vegan: false,
         thai: false,
         tapas: false,
         sushi_bar: false,
         sushi: false,
         steakhouse: true,
         south_american: false,
         seasonal_or_local: false,
         seafood: false,
         pizza: false,
         middle_eastern: false,
         mexican: false,
         korean: false,
         japanese: false,
         italian: false,
         indian: false,
         greek: false,
         german: false,
         fusion: false,
         french: false,
         chinese: false,
         british: false,
         bakery: false,
         asian: false,
         all_american: true } ],
    menu:
     [ { meal: 'Lunch',
         _id: '574c75715c1baee60d5014b6',
         categories:
          [ { category_name: 'Small Plates',
              _id: '574c75715c1baee60d5014ca',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d5014d0' },
                 { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d5014cf' },
                 { dish_name: 'Smoked Salmon Dip',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d5014ce' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, yuzu kosho, celtuse, wood sorrel',
                   _id: '574c75715c1baee60d5014cd' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d5014cc' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d5014cb' } ] },
            { category_name: 'Sandwiches',
              _id: '574c75715c1baee60d5014c4',
              dishes:
               [ { dish_name: 'Pulled Chicken Sandwich',
                   description: 'house bbq sauce, slaw, pickle',
                   _id: '574c75715c1baee60d5014c9' },
                 { dish_name: 'Grilled Cheese',
                   description: 'raclette, gruyere, cheddar, bechamel',
                   _id: '574c75715c1baee60d5014c8' },
                 { dish_name: 'Steak Sandwich',
                   description: 'shallot marmalade, horseradish, cream, arugula, steak sauce',
                   _id: '574c75715c1baee60d5014c7' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries ',
                   _id: '574c75715c1baee60d5014c6' },
                 { dish_name: 'Albacore Burger',
                   description: 'sriracha aoili, scallion, ginger, soy, avocado, furikake, sesame bun, fries',
                   _id: '574c75715c1baee60d5014c5' } ] },
            { category_name: 'Salads',
              _id: '574c75715c1baee60d5014be',
              dishes:
               [ { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d5014c3' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d5014c2' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d5014c1' },
                 { dish_name: 'Waldorf Salad',
                   description: 'potatoes, grapes, walnuts, mixed greens, herbed buttlermilk',
                   _id: '574c75715c1baee60d5014c0' },
                 { dish_name: 'Nicoise',
                   description: 'albacore, egg, olives, beans, tomatoes',
                   _id: '574c75715c1baee60d5014bf' } ] },
            { category_name: 'Mains',
              _id: '574c75715c1baee60d5014ba',
              dishes:
               [ { dish_name: 'Housemade Tagliatelle',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d5014bd' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d5014bc' },
                 { dish_name: 'Omelette',
                   description: 'cheddar, toast, greens',
                   _id: '574c75715c1baee60d5014bb' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d5014b7',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d5014b9' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d5014b8' } ] } ] },
       { meal: 'Dinner',
         _id: '574c75715c1baee60d501494',
         categories:
          [ { category_name: 'For the Table',
              _id: '574c75715c1baee60d5014b0',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d5014b5' },
                 { dish_name: 'Eggplant Caponata',
                   description: 'peppers, onions, olives, capers',
                   _id: '574c75715c1baee60d5014b4' },
                 { dish_name: 'Chicken Fritters',
                   description: 'adoba, black pepper aoili, serrano, pickled green garlic',
                   _id: '574c75715c1baee60d5014b3' },
                 { dish_name: 'Smoked Salmon Rillettes',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d5014b2' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d5014b1' } ] },
            { category_name: 'Small Plates',
              _id: '574c75715c1baee60d5014a7',
              dishes:
               [ { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d5014af' },
                 { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d5014ae' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d5014ad' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d5014ac' },
                 { dish_name: 'English Pea Risotto',
                   description: 'carrots, bacon, meyer lemon, pea tendrils',
                   _id: '574c75715c1baee60d5014ab' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, celtuse, sorrel',
                   _id: '574c75715c1baee60d5014aa' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d5014a9' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d5014a8' } ] },
            { category_name: 'Main',
              _id: '574c75715c1baee60d50149f',
              dishes:
               [ { dish_name: 'Housemade Fettuccine',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d5014a6' },
                 { dish_name: 'Grilled Branzino',
                   description: 'chermoula, braised escarole, lemon',
                   _id: '574c75715c1baee60d5014a5' },
                 { dish_name: 'Wood\'s Fishery Shrimp',
                   description: 'romesco, asparagus, aioli, parsley',
                   _id: '574c75715c1baee60d5014a4' },
                 { dish_name: 'Fire-roasted Chicken',
                   description: 'hummus, cucumber raita, grilled bread',
                   _id: '574c75715c1baee60d5014a3' },
                 { dish_name: 'Peads & Barnetts Pork Chop',
                   description: 'flageolets ragout, baby carrots, mustardd',
                   _id: '574c75715c1baee60d5014a2' },
                 { dish_name: 'Steak Frites',
                   description: '8 oz. new york prime, au poivre',
                   _id: '574c75715c1baee60d5014a1' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries',
                   _id: '574c75715c1baee60d5014a0' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d50149a',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d50149e' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d50149d' },
                 { dish_name: 'Grilled Sprouted Broccoli',
                   description: 'meyer lemon, basil',
                   _id: '574c75715c1baee60d50149c' },
                 { dish_name: 'Roasted Fingerling Potatoes',
                   description: '',
                   _id: '574c75715c1baee60d50149b' } ] },
            { category_name: 'Desserts',
              _id: '574c75715c1baee60d501495',
              dishes:
               [ { dish_name: 'Chocolate Chip Cookies and Cinnamon Milk',
                   description: '',
                   _id: '574c75715c1baee60d501499' },
                 { dish_name: 'Lemon Posset',
                   description: '',
                   _id: '574c75715c1baee60d501498' },
                 { dish_name: 'Chocolate Cake',
                   description: '',
                   _id: '574c75715c1baee60d501497' },
                 { dish_name: 'Blackberry Cobbler',
                   description: '',
                   _id: '574c75715c1baee60d501496' } ] } ] } ],
    meals:
     [ { _id: '574c75715c1baee60d5014d1',
         lunch: true,
         happy_hour: false,
         drinks: false,
         dinner: true,
         coffee: false,
         brunch: true,
         breakfast: false } ],
    tags:
     [ { _id: '574c75715c1baee60d5014d2',
         worth_the_lines: false,
         wine_bar: false,
         vegetarian_options: false,
         vegan_options: false,
         upscale: false,
         trendy: false,
         tasting_menu: false,
         takes_walk_ins: false,
         takes_dinner_reservations: false,
         take_out_options: false,
         sweet_treat: false,
         swanky: false,
         special_occasion: false,
         snack: false,
         small_plates: false,
         shareable: false,
         share_plates: false,
         secret: false,
         seat_yourself: false,
         scenery: false,
         rotating_menu: false,
         romantic: false,
         quiet: false,
         private_room: false,
         prime_location: false,
         pastries: false,
         outdoor_seating: false,
         outdoor_dining: false,
         organic_beer_and_wine: false,
         organic: false,
         order_at_counter: false,
         open_late: false,
         no_reservations: false,
         new_restaurant: false,
         locals: false,
         lively_bar_area: false,
         lively: false,
         karaoke: false,
         innovative: false,
         hotspot: false,
         hotel_dining: false,
         hidden_gem: false,
         healthy_options: false,
         hard_to_get_a_table: false,
         happy_hour: false,
         great_view: false,
         good_for_parents: false,
         good_for_lunch: false,
         good_for_groups: false,
         good_drinks: true,
         good_ambiance: false,
         gluten_free_options: false,
         gastropub: false,
         fusion: false,
         fun: false,
         foodie_famous: false,
         first_date: false,
         farm_to_table: false,
         fancy: false,
         famous_chef: false,
         family_friendly: false,
         dog_friendly: false,
         dietary_restriction_friendly: false,
         date_spot: false,
         date_night: false,
         communal_tables: false,
         classy: false,
         chef_inventive: false,
         celeb_spotting: false,
         casual: false,
         cafe: false,
         burgers: false,
         beer_selection: false,
         beer_and_wine: false,
         bar_seating: false,
         bar_scene: false,
         bar_area: false,
         bar: false,
         baked_goods: false,
         authentic_takeout: false,
         authentic: false,
         afternoon: false } ] },
  { _id: '574c75715c1baee60d5014d3',
    restaurantId: '3',
    name: 'Benihana',
    imgPath: 'https://drive.google.com/uc?export=view&id=0B7Q--fIbe5tbSFZoYnZLdlRaVzQ',
    location: 'Santa Monica',
    latitude: 34.0155274,
    longitude: -118.4938469,
    price: '20-30',
    address: '1447 4th St, Santa Monica, CA 90401',
    phone_number: '(310) 260-1423',
    reviews: '3.0/5',
    notes: '',
    website: 'http://www.benihana.com/',
    created_at: '2016-05-30T17:16:33.642Z',
    updated_at: '2016-05-30T17:16:33.642Z',
    __v: 0,
    food_types:
     [ { _id: '574c75715c1baee60d5014d4',
         vegan: false,
         thai: false,
         tapas: false,
         sushi_bar: false,
         sushi: false,
         steakhouse: false,
         south_american: false,
         seasonal_or_local: false,
         seafood: false,
         pizza: false,
         middle_eastern: false,
         mexican: false,
         korean: false,
         japanese: true,
         italian: false,
         indian: false,
         greek: false,
         german: false,
         fusion: false,
         french: false,
         chinese: false,
         british: false,
         bakery: false,
         asian: false,
         all_american: false } ],
    menu:
     [ { meal: 'Lunch',
         _id: '574c75715c1baee60d5014f7',
         categories:
          [ { category_name: 'Small Plates',
              _id: '574c75715c1baee60d50150b',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d501511' },
                 { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d501510' },
                 { dish_name: 'Smoked Salmon Dip',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d50150f' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, yuzu kosho, celtuse, wood sorrel',
                   _id: '574c75715c1baee60d50150e' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d50150d' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d50150c' } ] },
            { category_name: 'Sandwiches',
              _id: '574c75715c1baee60d501505',
              dishes:
               [ { dish_name: 'Pulled Chicken Sandwich',
                   description: 'house bbq sauce, slaw, pickle',
                   _id: '574c75715c1baee60d50150a' },
                 { dish_name: 'Grilled Cheese',
                   description: 'raclette, gruyere, cheddar, bechamel',
                   _id: '574c75715c1baee60d501509' },
                 { dish_name: 'Steak Sandwich',
                   description: 'shallot marmalade, horseradish, cream, arugula, steak sauce',
                   _id: '574c75715c1baee60d501508' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries ',
                   _id: '574c75715c1baee60d501507' },
                 { dish_name: 'Albacore Burger',
                   description: 'sriracha aoili, scallion, ginger, soy, avocado, furikake, sesame bun, fries',
                   _id: '574c75715c1baee60d501506' } ] },
            { category_name: 'Salads',
              _id: '574c75715c1baee60d5014ff',
              dishes:
               [ { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d501504' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d501503' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d501502' },
                 { dish_name: 'Waldorf Salad',
                   description: 'potatoes, grapes, walnuts, mixed greens, herbed buttlermilk',
                   _id: '574c75715c1baee60d501501' },
                 { dish_name: 'Nicoise',
                   description: 'albacore, egg, olives, beans, tomatoes',
                   _id: '574c75715c1baee60d501500' } ] },
            { category_name: 'Mains',
              _id: '574c75715c1baee60d5014fb',
              dishes:
               [ { dish_name: 'Housemade Tagliatelle',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d5014fe' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d5014fd' },
                 { dish_name: 'Omelette',
                   description: 'cheddar, toast, greens',
                   _id: '574c75715c1baee60d5014fc' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d5014f8',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d5014fa' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d5014f9' } ] } ] },
       { meal: 'Dinner',
         _id: '574c75715c1baee60d5014d5',
         categories:
          [ { category_name: 'For the Table',
              _id: '574c75715c1baee60d5014f1',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d5014f6' },
                 { dish_name: 'Eggplant Caponata',
                   description: 'peppers, onions, olives, capers',
                   _id: '574c75715c1baee60d5014f5' },
                 { dish_name: 'Chicken Fritters',
                   description: 'adoba, black pepper aoili, serrano, pickled green garlic',
                   _id: '574c75715c1baee60d5014f4' },
                 { dish_name: 'Smoked Salmon Rillettes',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d5014f3' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d5014f2' } ] },
            { category_name: 'Small Plates',
              _id: '574c75715c1baee60d5014e8',
              dishes:
               [ { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d5014f0' },
                 { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d5014ef' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d5014ee' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d5014ed' },
                 { dish_name: 'English Pea Risotto',
                   description: 'carrots, bacon, meyer lemon, pea tendrils',
                   _id: '574c75715c1baee60d5014ec' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, celtuse, sorrel',
                   _id: '574c75715c1baee60d5014eb' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d5014ea' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d5014e9' } ] },
            { category_name: 'Main',
              _id: '574c75715c1baee60d5014e0',
              dishes:
               [ { dish_name: 'Housemade Fettuccine',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d5014e7' },
                 { dish_name: 'Grilled Branzino',
                   description: 'chermoula, braised escarole, lemon',
                   _id: '574c75715c1baee60d5014e6' },
                 { dish_name: 'Wood\'s Fishery Shrimp',
                   description: 'romesco, asparagus, aioli, parsley',
                   _id: '574c75715c1baee60d5014e5' },
                 { dish_name: 'Fire-roasted Chicken',
                   description: 'hummus, cucumber raita, grilled bread',
                   _id: '574c75715c1baee60d5014e4' },
                 { dish_name: 'Peads & Barnetts Pork Chop',
                   description: 'flageolets ragout, baby carrots, mustardd',
                   _id: '574c75715c1baee60d5014e3' },
                 { dish_name: 'Steak Frites',
                   description: '8 oz. new york prime, au poivre',
                   _id: '574c75715c1baee60d5014e2' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries',
                   _id: '574c75715c1baee60d5014e1' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d5014db',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d5014df' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d5014de' },
                 { dish_name: 'Grilled Sprouted Broccoli',
                   description: 'meyer lemon, basil',
                   _id: '574c75715c1baee60d5014dd' },
                 { dish_name: 'Roasted Fingerling Potatoes',
                   description: '',
                   _id: '574c75715c1baee60d5014dc' } ] },
            { category_name: 'Desserts',
              _id: '574c75715c1baee60d5014d6',
              dishes:
               [ { dish_name: 'Chocolate Chip Cookies and Cinnamon Milk',
                   description: '',
                   _id: '574c75715c1baee60d5014da' },
                 { dish_name: 'Lemon Posset',
                   description: '',
                   _id: '574c75715c1baee60d5014d9' },
                 { dish_name: 'Chocolate Cake',
                   description: '',
                   _id: '574c75715c1baee60d5014d8' },
                 { dish_name: 'Blackberry Cobbler',
                   description: '',
                   _id: '574c75715c1baee60d5014d7' } ] } ] } ],
    meals:
     [ { _id: '574c75715c1baee60d501512',
         lunch: true,
         happy_hour: false,
         drinks: false,
         dinner: true,
         coffee: false,
         brunch: false,
         breakfast: false } ],
    tags:
     [ { _id: '574c75715c1baee60d501513',
         worth_the_lines: false,
         wine_bar: false,
         vegetarian_options: false,
         vegan_options: false,
         upscale: false,
         trendy: false,
         tasting_menu: false,
         takes_walk_ins: false,
         takes_dinner_reservations: false,
         take_out_options: false,
         sweet_treat: false,
         swanky: false,
         special_occasion: false,
         snack: false,
         small_plates: false,
         shareable: false,
         share_plates: false,
         secret: false,
         seat_yourself: false,
         scenery: false,
         rotating_menu: false,
         romantic: false,
         quiet: false,
         private_room: false,
         prime_location: false,
         pastries: false,
         outdoor_seating: false,
         outdoor_dining: false,
         organic_beer_and_wine: false,
         organic: false,
         order_at_counter: false,
         open_late: false,
         no_reservations: false,
         new_restaurant: false,
         locals: false,
         lively_bar_area: false,
         lively: false,
         karaoke: false,
         innovative: false,
         hotspot: false,
         hotel_dining: false,
         hidden_gem: false,
         healthy_options: false,
         hard_to_get_a_table: false,
         happy_hour: false,
         great_view: false,
         good_for_parents: false,
         good_for_lunch: false,
         good_for_groups: true,
         good_drinks: true,
         good_ambiance: false,
         gluten_free_options: false,
         gastropub: false,
         fusion: false,
         fun: false,
         foodie_famous: false,
         first_date: false,
         farm_to_table: false,
         fancy: false,
         famous_chef: false,
         family_friendly: false,
         dog_friendly: false,
         dietary_restriction_friendly: false,
         date_spot: false,
         date_night: false,
         communal_tables: false,
         classy: false,
         chef_inventive: false,
         celeb_spotting: false,
         casual: true,
         cafe: false,
         burgers: false,
         beer_selection: false,
         beer_and_wine: false,
         bar_seating: false,
         bar_scene: false,
         bar_area: false,
         bar: false,
         baked_goods: false,
         authentic_takeout: false,
         authentic: false,
         afternoon: false } ] },
  { _id: '574c75715c1baee60d501514',
    restaurantId: '4',
    name: 'Big Dean\'s Oceanfront Cafe',
    imgPath: 'https://drive.google.com/uc?export=view&id=0B7Q--fIbe5tbUEVQV21JaWxjMjg',
    location: 'Santa Monica',
    latitude: 34.0103344,
    longitude: -118.4954638,
    price: '<20',
    address: '1615 Ocean Front Walk, Santa Monica, CA 90401',
    phone_number: '(310) 393-2666',
    reviews: '4.0/5',
    notes: 'sports bar, day drinking',
    website: 'http://www.bigdeansoceanfrontcafe.com/',
    created_at: '2016-05-30T17:16:33.861Z',
    updated_at: '2016-05-30T17:16:33.861Z',
    __v: 0,
    food_types:
     [ { _id: '574c75715c1baee60d501515',
         vegan: false,
         thai: false,
         tapas: false,
         sushi_bar: false,
         sushi: false,
         steakhouse: false,
         south_american: false,
         seasonal_or_local: false,
         seafood: false,
         pizza: false,
         middle_eastern: false,
         mexican: false,
         korean: false,
         japanese: false,
         italian: false,
         indian: false,
         greek: false,
         german: false,
         fusion: false,
         french: false,
         chinese: false,
         british: false,
         bakery: false,
         asian: false,
         all_american: false } ],
    menu:
     [ { meal: 'Lunch',
         _id: '574c75715c1baee60d501538',
         categories:
          [ { category_name: 'Small Plates',
              _id: '574c75715c1baee60d50154c',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d501552' },
                 { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d501551' },
                 { dish_name: 'Smoked Salmon Dip',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d501550' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, yuzu kosho, celtuse, wood sorrel',
                   _id: '574c75715c1baee60d50154f' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d50154e' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d50154d' } ] },
            { category_name: 'Sandwiches',
              _id: '574c75715c1baee60d501546',
              dishes:
               [ { dish_name: 'Pulled Chicken Sandwich',
                   description: 'house bbq sauce, slaw, pickle',
                   _id: '574c75715c1baee60d50154b' },
                 { dish_name: 'Grilled Cheese',
                   description: 'raclette, gruyere, cheddar, bechamel',
                   _id: '574c75715c1baee60d50154a' },
                 { dish_name: 'Steak Sandwich',
                   description: 'shallot marmalade, horseradish, cream, arugula, steak sauce',
                   _id: '574c75715c1baee60d501549' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries ',
                   _id: '574c75715c1baee60d501548' },
                 { dish_name: 'Albacore Burger',
                   description: 'sriracha aoili, scallion, ginger, soy, avocado, furikake, sesame bun, fries',
                   _id: '574c75715c1baee60d501547' } ] },
            { category_name: 'Salads',
              _id: '574c75715c1baee60d501540',
              dishes:
               [ { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d501545' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d501544' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d501543' },
                 { dish_name: 'Waldorf Salad',
                   description: 'potatoes, grapes, walnuts, mixed greens, herbed buttlermilk',
                   _id: '574c75715c1baee60d501542' },
                 { dish_name: 'Nicoise',
                   description: 'albacore, egg, olives, beans, tomatoes',
                   _id: '574c75715c1baee60d501541' } ] },
            { category_name: 'Mains',
              _id: '574c75715c1baee60d50153c',
              dishes:
               [ { dish_name: 'Housemade Tagliatelle',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d50153f' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d50153e' },
                 { dish_name: 'Omelette',
                   description: 'cheddar, toast, greens',
                   _id: '574c75715c1baee60d50153d' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d501539',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d50153b' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d50153a' } ] } ] },
       { meal: 'Dinner',
         _id: '574c75715c1baee60d501516',
         categories:
          [ { category_name: 'For the Table',
              _id: '574c75715c1baee60d501532',
              dishes:
               [ { dish_name: 'Marinated Olives',
                   description: 'orange, thyme',
                   _id: '574c75715c1baee60d501537' },
                 { dish_name: 'Eggplant Caponata',
                   description: 'peppers, onions, olives, capers',
                   _id: '574c75715c1baee60d501536' },
                 { dish_name: 'Chicken Fritters',
                   description: 'adoba, black pepper aoili, serrano, pickled green garlic',
                   _id: '574c75715c1baee60d501535' },
                 { dish_name: 'Smoked Salmon Rillettes',
                   description: 'celery, scallions, aioli',
                   _id: '574c75715c1baee60d501534' },
                 { dish_name: 'Charcuterie Board',
                   description: 'selection of house made items',
                   _id: '574c75715c1baee60d501533' } ] },
            { category_name: 'Small Plates',
              _id: '574c75715c1baee60d501529',
              dishes:
               [ { dish_name: 'Nantes Carrot Soup',
                   description: 'ginger, lemongrass, yogurt, mint',
                   _id: '574c75715c1baee60d501531' },
                 { dish_name: 'Golden Quinoa Bowl',
                   description: 'roasted fennel, tangerine, almonds',
                   _id: '574c75715c1baee60d501530' },
                 { dish_name: 'Coleman Farms Green Salad',
                   description: 'beets, apple radish, pistachio, tarragon',
                   _id: '574c75715c1baee60d50152f' },
                 { dish_name: 'Kale Salad',
                   description: 'red cabbage, carrots, radish, blood orange',
                   _id: '574c75715c1baee60d50152e' },
                 { dish_name: 'English Pea Risotto',
                   description: 'carrots, bacon, meyer lemon, pea tendrils',
                   _id: '574c75715c1baee60d50152d' },
                 { dish_name: 'Hamachi Crudo',
                   description: 'kumquat, radish, celtuse, sorrel',
                   _id: '574c75715c1baee60d50152c' },
                 { dish_name: 'Octopus',
                   description: 'salted potatoes, eggplant, aji verde',
                   _id: '574c75715c1baee60d50152b' },
                 { dish_name: 'Root Vegertables',
                   description: 'weiser farms carrots, pink turnips, celery root, radish',
                   _id: '574c75715c1baee60d50152a' } ] },
            { category_name: 'Main',
              _id: '574c75715c1baee60d501521',
              dishes:
               [ { dish_name: 'Housemade Fettuccine',
                   description: 'lamb bolognese, parmesan',
                   _id: '574c75715c1baee60d501528' },
                 { dish_name: 'Grilled Branzino',
                   description: 'chermoula, braised escarole, lemon',
                   _id: '574c75715c1baee60d501527' },
                 { dish_name: 'Wood\'s Fishery Shrimp',
                   description: 'romesco, asparagus, aioli, parsley',
                   _id: '574c75715c1baee60d501526' },
                 { dish_name: 'Fire-roasted Chicken',
                   description: 'hummus, cucumber raita, grilled bread',
                   _id: '574c75715c1baee60d501525' },
                 { dish_name: 'Peads & Barnetts Pork Chop',
                   description: 'flageolets ragout, baby carrots, mustardd',
                   _id: '574c75715c1baee60d501524' },
                 { dish_name: 'Steak Frites',
                   description: '8 oz. new york prime, au poivre',
                   _id: '574c75715c1baee60d501523' },
                 { dish_name: 'Grass Fed Cheeseburger',
                   description: 'lettuce, tomato, onion, marmalade, 1000 island, fries',
                   _id: '574c75715c1baee60d501522' } ] },
            { category_name: 'Sides',
              _id: '574c75715c1baee60d50151c',
              dishes:
               [ { dish_name: 'Brussel Sprouts',
                   description: 'oro blanco, pear mostarda',
                   _id: '574c75715c1baee60d501520' },
                 { dish_name: 'Herbed French Fries',
                   description: '',
                   _id: '574c75715c1baee60d50151f' },
                 { dish_name: 'Grilled Sprouted Broccoli',
                   description: 'meyer lemon, basil',
                   _id: '574c75715c1baee60d50151e' },
                 { dish_name: 'Roasted Fingerling Potatoes',
                   description: '',
                   _id: '574c75715c1baee60d50151d' } ] },
            { category_name: 'Desserts',
              _id: '574c75715c1baee60d501517',
              dishes:
               [ { dish_name: 'Chocolate Chip Cookies and Cinnamon Milk',
                   description: '',
                   _id: '574c75715c1baee60d50151b' },
                 { dish_name: 'Lemon Posset',
                   description: '',
                   _id: '574c75715c1baee60d50151a' },
                 { dish_name: 'Chocolate Cake',
                   description: '',
                   _id: '574c75715c1baee60d501519' },
                 { dish_name: 'Blackberry Cobbler',
                   description: '',
                   _id: '574c75715c1baee60d501518' } ] } ] } ],
    meals:
     [ { _id: '574c75715c1baee60d501553',
         lunch: false,
         happy_hour: false,
         drinks: false,
         dinner: false,
         coffee: false,
         brunch: false,
         breakfast: false } ],
    tags:
     [ { _id: '574c75715c1baee60d501554',
         worth_the_lines: false,
         wine_bar: false,
         vegetarian_options: false,
         vegan_options: false,
         upscale: false,
         trendy: false,
         tasting_menu: false,
         takes_walk_ins: false,
         takes_dinner_reservations: false,
         take_out_options: false,
         sweet_treat: false,
         swanky: false,
         special_occasion: false,
         snack: false,
         small_plates: false,
         shareable: false,
         share_plates: false,
         secret: false,
         seat_yourself: false,
         scenery: false,
         rotating_menu: false,
         romantic: false,
         quiet: false,
         private_room: false,
         prime_location: false,
         pastries: false,
         outdoor_seating: false,
         outdoor_dining: false,
         organic_beer_and_wine: false,
         organic: false,
         order_at_counter: false,
         open_late: false,
         no_reservations: false,
         new_restaurant: false,
         locals: false,
         lively_bar_area: true,
         lively: false,
         karaoke: false,
         innovative: false,
         hotspot: false,
         hotel_dining: false,
         hidden_gem: false,
         healthy_options: false,
         hard_to_get_a_table: false,
         happy_hour: false,
         great_view: false,
         good_for_parents: false,
         good_for_lunch: false,
         good_for_groups: false,
         good_drinks: false,
         good_ambiance: false,
         gluten_free_options: false,
         gastropub: false,
         fusion: false,
         fun: false,
         foodie_famous: false,
         first_date: false,
         farm_to_table: false,
         fancy: false,
         famous_chef: false,
         family_friendly: false,
         dog_friendly: false,
         dietary_restriction_friendly: false,
         date_spot: false,
         date_night: false,
         communal_tables: false,
         classy: false,
         chef_inventive: false,
         celeb_spotting: false,
         casual: true,
         cafe: false,
         burgers: false,
         beer_selection: false,
         beer_and_wine: false,
         bar_seating: false,
         bar_scene: false,
         bar_area: false,
         bar: false,
         baked_goods: false,
         authentic_takeout: false,
         authentic: false,
         afternoon: false } ] } ];
const COLOR_WHITE = '#EDEDED';

class SearchResults extends Component {

    constructor(props) {
        super(props);

        var dataSource = new ListView.DataSource(
            {rowHasChanged: (r1, r2) => r1.thumb_url !== r2.thumb_url});
        this.state = {
            // dataSource: dataSource.cloneWithRows(LISTING)
            dataSource: dataSource.cloneWithRows(this.props.listings)
        }
        // console.log('HEVJBENSM');
        // console.log(this.props.bookmarks);
    }

    rowPressed(restaurantGUID) {
        var data = this.props.listings.filter(prop => prop.name === restaurantGUID)[0];
        var bookmarked = this.props.bookmarks.includes(data._id);
        // console.log('HII' + bookmarked);

        this.props.navigator.push({
            title: restaurantGUID,
            component: RestaurantView,
            passProps: {data: data, bookmarked: bookmarked},
            barTintColor: 'black',
            tintColor: COLOR_WHITE,
            titleTextColor: COLOR_WHITE,
            leftButtonIcon: require('./Resources/icon_left.png'),
            onLeftButtonPress: () => {
              this.props.navigator.pop();
            }
        });
    }

    renderRow(rowData) {
        return (
            <TouchableHighlight onPress={() => this.rowPressed(rowData.name)} underlayColor='#dddddd'>
                <View>
                    <View style={css.rowContainer}>
                        <Image style={css.thumb} source={{uri: rowData.imgPath}}/>
                        <View style={[css.textContainer]}>
                            <Text style={[css.restaurantTitle]}>{rowData.name}</Text>
                            <Text style={[css.restaurantLocation]} numberOfLines={1}>{rowData.location}</Text>
                        </View>
                    </View>
                    <View style={css.separator}/>
                </View>
            </TouchableHighlight>
        );
    }

    render() {
      return (
        <Image source={require('./Resources/landing_background_4.jpg')} style={css.container}>
          <ListView
            dataSource={this.state.dataSource}
            renderRow={this.renderRow.bind(this)}/>
        </Image>
      );
    }
}

module.exports = SearchResults;
